apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-psi-exporter
  namespace: monitor
spec:
  selector:
    matchLabels: 
      app: pod-psi-exporter
  template:
    metadata:
      labels:
        app: pod-psi-exporter
    spec:
      serviceAccountName: pod-psi-exporter-sa
      terminationGracePeriodSeconds: 5
      hostPID: true
      hostNetwork: true
      nodeSelector:
          kubernetes.io/os: linux
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        project: optum
      containers:
        - name: pod-psi-exporter
          image: nicklin9907/exporters:pod-psi-exporter-v2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 2333
            hostPort: 2333
            protocol: TCP
            name: metrics
          securityContext:
            capabilities:
              add: ["SYS_PTRACE","SYS_ADMIN"]
          env:
            - name: PORT
              value: "2333"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONTAINER_RUNTIME
              value: "docker"
            - name: CONTAINER_RUNTIME_PATH
              value: unix:///var/run/docker.sock
            - name: PSI_INTERVAL
              value: "1"
            - name: PERF_INTERVAL
              value: "5"
            - name: CGROUP_BASE_DIR
              value: "/root/cgroup"
            - name: PROC_BASE_DIR
              value: "/root/proc"
            - name: DOCKER_BASE_DIR
              value: "/root/docker"
            - name: PERF_BASE_DIR
              value: "/sys"
            - name: PERF_COLLECTOR_ENABLED
              value: "false"
            - name: PSI_COLLECTOR_ENABLED
              value: "true"
          resources:
            requests:
              cpu: 200m
              memory: "200Mi"
            limits:
              cpu: 200m
              memory: "500Mi"
          volumeMounts:
            - name: dockerpath
              mountPropagation: HostToContainer
              mountPath: /root/docker
              readOnly: true
            - name: procpath
              mountPropagation: HostToContainer
              mountPath: /root/proc
              readOnly: true
            - name: cgrouppath
              mountPropagation: HostToContainer
              mountPath: /root/cgroup
              readOnly: true
            - name: perfpath
              mountPropagation: HostToContainer
              mountPath: /sys
              readOnly: true
            - name: containerdsock
              mountPropagation: HostToContainer
              mountPath: /run/containerd/
              readOnly: true
      volumes:
        - name: dockerpath
          hostPath:
            path: /var/lib/docker
            type: Directory
        - name: procpath
          hostPath:
            path: /proc
            type: Directory
        - name: cgrouppath
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: perfpath
          hostPath:
            path: /sys
            type: Directory
        - name: containerdsock
          hostPath:
            path: /run/containerd
---
apiVersion: v1
kind: Service
metadata:
  name: pod-psi-exporter-service
  namespace: monitor
  labels:
    app: pod-psi-exporter
spec:
  selector:
    app: pod-psi-exporter
  ports:
    - port: 2333
      protocol: TCP
      name: exporter-port
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitor
  name: pod-psi-exporter
  labels:
    app: pod-psi-exporter
    release: monitor
spec:
  selector:
    matchLabels:
      app: pod-psi-exporter
  namespaceSelector:
    matchNames:
      - monitor
  endpoints:
  - port: exporter-port
    interval: 1s
    relabelings:
    - sourceLabels: 
      - __meta_kubernetes_endpoint_node_name
      targetLabel: node
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-psi-exporter-sa
  namespace: monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-psi-exporter
rules:
- apiGroups: [""]
  resources:
  - nodes/proxy
  - nodes
  - namespaces
  - endpoints
  - pods
  - services
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources:
  - nodes/metrics
  verbs: ["get"]
- nonResourceURLs:
  - /metrics
  verbs: ["get"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-psi-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-psi-exporter
subjects:
- kind: ServiceAccount
  name: pod-psi-exporter-sa
  namespace: monitor